# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    # Locations of package manifests. This is searching the root directory, and all current modules of this project for pom.xmls.
    # You will need to update this every time a module is added or removed.
    directories:
      - "/"
      - "/api"
      - "/bot"
      - "/data-model"
    schedule:
      interval: "weekly"
