package me.longbow122;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;

@SpringBootApplication
@ConfigurationPropertiesScan("me.longbow122.configuration.properties")
public class JdaSpringQuickstartApplication {

    //TODO SEE IF WE CAN GET THE APPLICATION PROPERTIES FILE TO APPEAR DURING RUNTIME LIKE A REAL CONFIG FILE.
    // WE NEED THE CONFIG FILE TO BE SPUN UP, AND FOR THINGS TO FAIL IF THE CONFIG FILE IS NOT PRESENT.
    // IF NOT PRESENT, THEN WE NEED TO CREATE THE FILE AND FAIL AS LONG AS WE HAVE NOT GIVEN IT A TOKEN TO USE.

    //TODO ALSO NEED TO ENSURE THAT WE CREATE A FLATFILE DB IN THE SAME DIRECTORY AS THE JAR WHEN RUNNING. DO WE NEED TO COMPILE DATA-MODEL?
    // FLATFILE MUST BE CREATED WITH TABLE INITIALISED ON STARTUP. NEED TO FINDOUT HOW WE ARE GOING TO GET THAT PART DONE.

    //TODO NEED TO ENSURE THAT DATA-MODEL JAR IS JUST A LIBRARY JAR, WE NEED TO BE COMPILING IT WITHIN BOT MODULE! API CAN RUN SEPARATELY IF NEEDED, BUT NEEDS TO BE REFERRING TO
    // BOT MODULE METHODS

    //TODO NEED TO IMPLEMENT ALL COPYPASTA FUNCTIONALITY AS WELL.
    // DATA-MODEL METHODS SHOULD BE HANDLING ALL CALLS AND WORK TO THE DB FLATFILE, WHICH NEEDS TO BE CREATED WHEN THE DB STARTS.

    public static void main(String[] args) {
        SpringApplication.run(JdaSpringQuickstartApplication.class, args);
    }

}
