spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  application:
    name: bot
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./data'
    username: sa
    password: password
  data:
    jdbc:
      dialect: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update