package me.longbow122.bot.configuration.properties;

import jakarta.validation.constraints.Size;
import org.springframework.boot.context.properties.ConfigurationProperties;

import java.util.List;
import java.util.Map;

@ConfigurationProperties(prefix = "form")
public record FormConfigurationProperties(
	@Size(max = 25)
	Map<String, Form> forms
) {

	//TODO COULD WE POTENTIALLY MAKE OUR OWN CONFIG MODALS TO ALLOW FOR FORMS TO BE ADDED AND INJECTED INTO THE CONFIG FILE THROUGH A SLASH COMMAND?
	// WE COULD USE ONE MODAL TO LET PEOPLE INSERT THE QUESTIONS, AND THEN THE OTHER MODAL TO ALLOW PEOPLE TO INSERT THE PLACEHOLDERS FOR THE FORM!
	// THEY WOULD THEN BE ABLE TO ADD THE CHANNEL THAT THE FORM WOULD SEND TO IN THE SLASH COMMAND, AS WELL AS THE NAME OF THE FORM!

	//TODO WE ALSO NEED TO FIND A WAY TO RELOAD THE CONFIG FILE, SO THAT WE CAN APPLY AND USE THE NEW PROPERTIES ON THE FLY!
	// OTHERWISE, WE WOULD NEED TO RESTART THE BOT TO APPLY NEW CONFIG CHANGES!

	//TODO COULD WE ALSO ALLOW FOR EDITING OF FORMS THROUGH A SIMILAR MODAL SYSTEM?
	// NEEDS TO BE THOUGHT THROUGH?

	//TODO COULD WE FIND A WAY TO PROPERLY HANDLE CONFIGURATION VALIDATION, TO ENSURE THAT THE FORMS WE HAVE FOUND WITHIN THE CONFIG FILE ARE VALID?
	// WE ARE CURRENTLY DOING VALIDATION INSIDE THE COPYPASTA COMMAND LISTENER, THIS SHOULD IDEALLY BE DONE HERE!
	public record Form(
		long formChannel,
		List<String> questions,
		List<String> placeholders
	) {
	}
}