name: release.yml
on:
  push:
    branches: [ "main" ]

jobs:
  release_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: 'true'
        #TODO GOING TO NEED TO CARRY OVER ANY CHANGES WE MAKE TO ENSURE THAT TEST CLASSES ARE PICKED UP BY MAVEN TO HERE
        #TODO SINCE THIS USES THE SAME STUFF.
      - name: Build with Maven
        run: mvn clean install
      #TODO NEED TO FIND A GOOD WAY OF GETTING THE FILEPATHS, SINCE OUR VERSION NUMBERING WILL BE BUMPED IN NEW VERSIONS.
      #TODO WE COULD LIKELY USE THIS ACTION TO HANDLE PUSHING TO RELEASES. ONLY ISSUE IS GETTING THE RIGHT VERSION NAMES FROM THE BUMPED VERSIONS.
      #TODO NEED TO FIND A WAY TO OUTPUT THE RIGHT BUMPED VERSIONS FOR EACH FILE, ALONG WITH HANDLE BUMPING.
      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        #TODO WOULD BE NICE IF WE COULD GATE THE UPLOADING OF ASSETS AND THE CREATION OF A RELEASE BEHIND SOME FORM OF CONDITION. NEED TO SEE HOW THIS CAN BE DONE.
        with:
          name: "Current Version"
          make_latest: true
          tag_name: ${{ github.ref_name}}${{github.run_id}}
          files: |
            api/target/suggest-a-laptop-bot-api-1.0.0.jar
            bot/target/suggest-a-laptop-bot-bot-1.0.0.jar
            data-model/target/suggest-a-laptop-bot-data-model-1.0.0.jar
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4.1.1
